# Generated by Django 2.1.11 on 2019-09-04 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdadb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationndc',
            name='medication_strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndcs', to='fdadb.MedicationStrength'),
        ),
        migrations.AlterField(
            model_name='medicationstrength',
            name='medication_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='fdadb.MedicationName'),
        ),
    ]
